### ISSUE TITLE
Ampliación de la clase User

### ISSUE THREAD

**Issue by ATorreclla** [ATorreclla/IWVG.SwC.AgustinTorrecilla#1]
Ver la descripción en [enlace wiki](https://github.com/ATorreclla/IWVG.SwC.AgustinTorrecilla/wiki/Ampliaci%C3%B3n-de-la-clase-User) Fecha entrega antes de 29/09/2018

**Comment by ropili19** [comment]
Se ha concluido el desarrollo del ticket , los cambios ya se encuentran en la rama develop.
