### ISSUE TITLE
Ampliación de la clase Fraction - Resultado Entero

### ISSUE THREAD

**Issue by ATorreclla** [ATorreclla/IWVG.SwC.AgustinTorrecilla#2]
Descripción de la ampliación en [descripción wiki](https://github.com/ATorreclla/IWVG.SwC.AgustinTorrecilla/wiki/Ampliaci%C3%B3n-de-la-clase-Fraction-Resultado-Entero) Fecha de entrega antes de 29/09/2018

**Comment by ropili19** [comment]
Se realiza lo indicado en el issue#2 con su correspondiente test.
