### ISSUE TITLE
Ampliación de la clase Point

### ISSUE THREAD

**Issue by ATorreclla** [ATorreclla/IWVG.SwC.AgustinTorrecilla#3]
Descripción de la ampliación en [enlace wiki](https://github.com/ATorreclla/IWVG.SwC.AgustinTorrecilla/wiki/Ampliaci%C3%B3n-de-la-clase-Point) Fecha de entrega antes de 29/09/2018

**Comment by jolomoreno** [comment]
Ya están hechas las mejoras y subidas al repositorio, he visto que la ejecución de Travis CI ha fallado pero por mi parte han pasado TODOS los tests y también he probado a ejecutar el comando "mvn package" para compilar todo el proyecto y también lo ejecuta con éxito. Puede ser por una mala configuración del SonarCloud?
